# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Bitbucket Cloud CLI with GitHub CLI ergonomics"
  homepage "https://github.com/uehatsu/bb"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uehatsu/bb/releases/download/v0.1.4/bb_0.1.4_darwin_amd64.tar.gz"
      sha256 "7f430779623c6fa285a490695de42d40be289b71492060cf55d03129e3f859f9"

      define_method(:install) do
        bin.install "bb"
        generate_completions_from_executable(bin/"bb", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uehatsu/bb/releases/download/v0.1.4/bb_0.1.4_darwin_arm64.tar.gz"
      sha256 "4433740e451a51ab24452bef3080ed8e06b4b3bb5b4847f1ba4dd48ddb19e9e1"

      define_method(:install) do
        bin.install "bb"
        generate_completions_from_executable(bin/"bb", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uehatsu/bb/releases/download/v0.1.4/bb_0.1.4_linux_amd64.tar.gz"
      sha256 "161541127604ad924033df54c34e42c939a7ea00da8d6eb276cb8ad88c14600c"
      define_method(:install) do
        bin.install "bb"
        generate_completions_from_executable(bin/"bb", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uehatsu/bb/releases/download/v0.1.4/bb_0.1.4_linux_arm64.tar.gz"
      sha256 "78e57feb1750789974f5a4757005adabbadc86e8c44ab8eeba77140d17b769ec"
      define_method(:install) do
        bin.install "bb"
        generate_completions_from_executable(bin/"bb", "completion")
      end
    end
  end

  test do
    system "#{bin}/bb", "version"
  end
end
